### ISSUE TITLE
NoClassDefFoundError: javax/servlet/ServletOutputStream

### ISSUE THREAD

**Issue by PerfectCarl** [davidB/livereload-jvm#6]
I'm trying to use livereload with jetty `9.2.10.v20150310` and I got this error: 

```
Caught unexpected exception: java.lang.NoClassDefFoundError: javax/servlet/ServletOutputStream

java.lang.NoClassDefFoundError: javax/servlet/ServletOutputStream
    at net_alchim31_livereload.LRServer.init(LRServer.java:31)
    at net_alchim31_livereload.LRServer.start(LRServer.java:77)
    at net_alchim31_livereload.LRServer.run(LRServer.java:84)
    at ninja.command.RunCommand.configureLivereload(RunCommand.java:403)
    at ninja.command.RunCommand.execute(RunCommand.java:261)
    at ninja.cmd.Main.execute(Main.java:43)
    at ninja.cmd.Main.main(Main.java:17)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletOutputStream
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 7 more
```

Do you know what is wrong?

**Comment by davidB** [comment]
Can I close this issue ?

**Comment by PerfectCarl** [comment]
Livereload doesn't support jetty 9.x at the moment
